"""Book Resource model

Revision ID: e1b2ce6ef7e7
Revises: d9c89644b5e9
Create Date: 2024-09-22 06:10:38.212397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b2ce6ef7e7'
down_revision = 'd9c89644b5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secret_text', sa.String(), server_default='ok', nullable=False))
        batch_op.add_column(sa.Column('reader_pk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'readers', ['reader_pk'], ['pk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reader_pk')
        batch_op.drop_column('secret_text')
        batch_op.drop_column('description')

    op.drop_table('readers')
    # ### end Alembic commands ###
